apiVersion: 1

datasources:
  - name: WazuhIndexer
    type: opensearch
    access: proxy
    url: http://172.22.0.11:9200
    database: "wazuh-alerts-*"
    isDefault: true
    editable: true
    jsonData:
      timeField: "timestamp"
      esVersion: "7.10.2"
      tlsMode: "disable"
      authEnabled: false
      timeInterval: "1s"

  - name: TheHive
    type: elasticsearch
    access: proxy
    url: http://172.22.0.31:9200
    database: "thehive*"
    editable: true
    jsonData:
      timeField: "_source.createdAt"
      esVersion: "7.10.2"
      tlsMode: "disable"

  - name: MISP
    type: mysql
    access: proxy
    url: 172.22.0.21:3306
    database: misp
    user: misp
    secureJsonData:
      password: ${MISP_DB_PASSWORD}
    jsonData:
      timeField: "timestamp"

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
